### ISSUE TITLE
Componentize this!

### ISSUE THREAD

**Issue by thomasbritton** [bradcliffe/skeleton.scss#2]
What I mean by 'componentize' is really move parts of the file into different modules and import as necessary.

Much easier to read, maintain and follow whats happening.

**Comment by SmileyJames2** [comment]
+1

**Comment by bsradcliffe** [comment]
Hi Thomas! You know, this was actually my initial approach to things. I had skeleton.scss importing Normalize as SASS and pretty much all sections of the table of contents were living inside of their own partial files, like so:

```
Skeleton/
├── skeleton.scss
├── _normalize.scss
└── skeleton/
       ├── components/
       └── _functions.scss
       └── _mixins.scss
       └── _settings.scss
```

My main concern was that Skeleton is so lightweight and has so few rules, they can't really be considered components. So while it makes sense to go with this architecture on perhaps a much more fleshed out framework like Foundation that handles modals, dropdowns, etc., it felt awkward having a `_clearing.scss` file that only imported one ruleset. Normalize.scss follows the same dogma, I believe. Since most of what it deals with are strictly element resets, it doesn't separate them out into individual partials for importing.

I guess it's more a matter of weighing the utility of allowing people to pick and choose what to `@import`, however. I'll reconsider this as I keep learning about SASS architectures.

**Comment by bsradcliffe** [comment]
So I went ahead and rolled back to the prior planned structure. Hopefully this will ease things. Even I was running into areas where I found componentization pretty nifty in such a small framework.
